services:
  api:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - redis
    container_name: api
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    hostname: redis
    container_name: redis